### ISSUE TITLE
KeyError (key not found: :ciphers)

### ISSUE THREAD

**Issue by catsky** [zillou/shrine-aliyun-oss#2]
following your readme, when try to save the image file, it reports error
```
>Product.create logo: File.open("1.jpeg")
Traceback (most recent call last):
        1: from (irb):1
KeyError (key not found: :ciphers)
```

**Comment by zillou** [comment]
@catsky Thank you for letting me know the issue. 
I did a quick search about the error you encountered, and I believe it's from rest-client. Can you please check the version of rest-client you are using by running `bundle show rest-client` from your project root?

**Comment by catsky** [comment]
/Users/catsky/.rvm/gems/ruby-2.5.1/gems/rest-client-2.0.2

**Comment by catsky** [comment]
and also, if I defined customised style on OSS, how can I get that kind of url?

your url function seems not allow extra params....
```
  def url(id, sign: true, expiry: 900)
        bucket.object_url(object_key(id), sign, expiry)
      end
```

![image](https://user-images.githubusercontent.com/367994/45008204-a6f2e100-b044-11e8-95cf-d6916ab46376.png)

**Comment by zillou** [comment]
For the rest-client error, maybe you can check this issue: https://github.com/rest-client/rest-client/issues/612 . I'm afraid I could not help unless I can remove the dependence of aliyun-oss-ruby.

For the `url` method, as you can I see,  it's simply a proxy of `aliyun-oss-ruby-sdk`, unfortunately, it does not support that thing, either.

https://github.com/aliyun/aliyun-oss-ruby-sdk/blob/fe066653376271b27c4cf835ba42c30b2fe982e9/lib/aliyun/oss/bucket.rb#L593-L628
