### ISSUE TITLE
A problem with download file in shrine version 2.16.0

### ISSUE THREAD

**Issue by weiWang95** [zillou/shrine-aliyun-oss#3]
Shrine version 2.16.0
problem: Only part of the file size can be downloaded.
example: 1M files can only be downloaded at 100kb

**Comment by zillou** [comment]
抱歉刚刚才看到你的问题？因为我自己并没有再使用这个 Gem，所以维护不是很活跃。

请问这个问题解决了吗？如果还没有的话，是否有更详细一点的问题说明?

**Comment by zillou** [comment]
@weiWang95 我刚刚发布了一个新版本，修复了直接调用 `download` 下载文件的问题。不知是否能解决你提到的问题。麻烦你反馈一下结果。
