### ISSUE TITLE
Basic direct upload?

### ISSUE THREAD

**Issue by waruboy** [zillou/shrine-aliyun-oss#4]
Hello!

First, thank you for your gem, I've been using it in my project and it is really useful.
I can't figure out if there is basic direct upload provided by your gem. Can I do something similar with this?
https://github.com/shrinerb/shrine/blob/master/doc/direct_s3.md#strategy-b-static

If you can give me some pointer I will be really grateful

**Comment by zillou** [comment]
I'm sorry, @waruboy. I didn't notice this issue until now.

I'll look into this issue, and see if I can implement the `presign` method, I think if we can mimic the s3 storage's [`presign` method](https://shrinerb.com/rdoc/classes/Shrine/Storage/S3.html#method-i-presign), the direct upload feature will be automatically available. 

I'll keep you updated.

**Comment by zillou** [comment]
Here's an example that might help, https://help.aliyun.com/document_detail/91870.html?spm=a2c4g.11186623.2.18.2ff87eaeFMRIvv#concept-fqm-tjz-2fb.

@waruboy if you can follow the example, you should be able to implement a direct upload to aliyun server.

**Comment by waruboy** [comment]
@zillou Thank you very much for the pointer! I will try to follow it. Looking forward if the gem can support direct upload
